run-name: patch new FW version
on: workflow_dispatch
#  schedule:
#		 every day, check for a new version
#  	 - cron: '0 12 * * *'

jobs:
  version-check:
    runs-on: ubuntu-latest
    outputs:
      status: ${{steps.run-step.outputs.status}}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          check-latest: true
          cache: 'pip'
      - run: pip install -r requirements.txt
      - name: Check for New Version
        id: run-step
        run: 'echo status=$(python3 versioncheck.py ${{secrets.PD_ACCESS_TOKEN}}) >> "$GITHUB_OUTPUT"'
  fw-patch:
    runs-on: ubuntu-latest
    needs: version-check
    if: needs.version-check.outputs.status != 'No content' && needs.version-check.outputs.status != 'Error'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          check-latest: true
          cache: 'pip'
      - run: pip install -r requirements.txt
      - run: mkdir -p static/ota_payload
      - name: Download and Patch Firmware
        env:
          VERSION: ${{needs.version-check.outputs.status}}
        run: 'python3 pdpatcher.py -t ${{secrets.PD_ACCESS_TOKEN}} -p ${{secrets.PD_PASSWORD}} -o static/ota_payload'
      - name: Package Firmware
        run: 'zip -r static/ota_payload.bin static/ota_payload'
      - name: Remove Old JSON Response
        run: 'rm -f static/index.html'
      - name: Create JSON Response
        run: 'python3 genresp.py > static/index.html'
      - name: Setup GitHub Pages
        uses: actions/configure-pages@v3
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'static/'

  deploy:
    needs: fw-patch
    permissions:
      pages: write
      id-token: write
    environment:
      name: 'github-pages'
      url: ${{steps.deployment.outputs.page_url}}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
