name: patch new FW version
on:
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:
    
jobs:
  version-check:
    runs-on: ubuntu-latest
    outputs:
      status: ${{steps.run-step.outputs.status}}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          check-latest: true
          cache: 'pip'
      - run: pip install -r requirements.txt
      - name: Fetch Old Version Number
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          file: 'update.json'
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Check for New Version
        id: run-step
        run: 'echo status=$(python3 versioncheck.py ${{secrets.PD_ACCESS_TOKEN}}) >> "$GITHUB_OUTPUT"'
  fw-patch:
    runs-on: ubuntu-latest
    needs: version-check
    permissions:
      contents: write
    if: needs.version-check.outputs.status != 'No content' && needs.version-check.outputs.status != 'Error'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          check-latest: true
          cache: 'pip'
      - run: pip install -r requirements.txt
      - run: mkdir -p static/ota_payload
      - name: Download and Patch Firmware
        run: 'python3 pdpatcher.py -k ${{secrets.PD_MFLT_KEY}} -t ${{secrets.PD_ACCESS_TOKEN}} -p ${{secrets.PD_PASSWORD}} -o static/ota_payload'
      - name: Package Firmware
        run: '(cd static/ota_payload && zip -r ../Playdate-dvt1.pdfw dvt1/* && zip -r ../Playdate-h7d1.pdfw h7d1/*)'
      - name: Remove Old JSON Response
        run: 'rm -f static/update.json'
      - name: Create JSON Response
        run: 'python3 genresp.py ${{needs.version-check.outputs.status}} > static/update.json'
      - name: Remove ota_payload
        run: 'rm -rf static/ota_payload'
      - name: Scrape Changelog
        run: 'python3 getchangelog.py ${{needs.version-check.outputs.status}} > description.html'
      - name: Publish Release
        uses: ncipollo/release-action@v1.13.0
        with:
          artifacts: static/*
          makeLatest: true
          tag: ${{needs.version-check.outputs.status}}
          bodyFile: description.html
